### ISSUE TITLE
set_per_page exception

### ISSUE THREAD

**Issue by totycro** [salesking/salesking_python_sdk#4]
I get the following in set_per_page:

  File "..../salesking/collection.py", line 71, in set_per_page
    if isinstance(int,entries) and entries <=100:
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

Apparently, the arguments of isinstance are switched and it should be isinstance(entries, int)

**Comment by FrankBie** [comment]
Hi Totycro, 
I will look into this during the day... sparetime project....
Thanks for your patience

**Comment by FrankBie** [comment]
fixed
