### ISSUE TITLE
Can't get paging to work

### ISSUE THREAD

**Issue by totycro** [salesking/salesking_python_sdk#5]
Hi,

Could you provide a simle example of how to deal with pages or how to use autoloading?
I've tried to use it along the following lines, but it seems that I always only get the first page, but multiple times:

    col = collection.get_collection_instance("contact")
    col.load()
    for x in xrange(1, col.get_total_pages()):
        col.load(x)
        # should I access col.items here?
    # or here?

Also, when setting autoload to True, I get this:
  File "...../salesking/collection.py", line 279, in _post_load
    if(self.autoload == True and self.total_pages > 1 and page == None):
NameError: global name 'page' is not defined

**Comment by FrankBie** [comment]
Hi,
paging seems to be broken currently - but it should work like this...

col = collection.get_collection_instance("contact")
col.load()
first_page_items = col.get_items()
for x in xrange(1, col.get_total_pages()):
   # for some reason the access to the items fails randomly currently - needs more investigation 
   col.load(page=x)
all_items = col.get_items()
# col.clear_items() if you do not want to append

**Comment by FrankBie** [comment]
Hi,
the Pageing testcase is working now, please update...
